```{r setup, echo=FALSE}
require(ggplot2, quietly=T)
```

# Analysis: Multiple Numerics by 1 factor

## Inputs

Selected numeric variables in dataframe mydf
```{r allnumerics, echo=FALSE, results="asis"}
cat("* ")
cat(numericlist, sep="\n* ")
```

Factor = factor1

<% if (nlevels(mydf$factor1)==3) { %>

## T-Test table

```{r ttesttable, results="asis", echo=T}

getstars = function(x) {
  if (x<0.001) return("***")
  if (x<0.01) return("**")
  if (x<0.05) return("*")
  return("")
}

getttest = function(mynumeric, sigfig=2) {
  template = paste("%.",sigfig,"f (%.",sigfig,"f)",sep="")
  n1 = mydf[mydf$factor1 == levels(mydf$factor1)[1], mynumeric]
  n2 = mydf[mydf$factor1 == levels(mydf$factor1)[2], mynumeric]
  pval=t.test(n1,n2)$p.value
  return(c(
    sprintf(template, mean(n1,na.rm=T), sd(n1,na.rm=T)),
    sprintf(template, mean(n2,na.rm=T), sd(n2,na.rm=T)),
    paste(format.pval(pval, eps=0.0001), getstars(pval), sep="")))
  
}

tbl=t(sapply(numericlist, getttest, 2))
colnames(tbl) = c(levels(mydf$factor1)[1], levels(mydf$factor1)[2], "p")

kable(tbl, format="html", table.attr='class="data table table-bordered table-condensed"')
```

<% } %>

## Mixed effects models

Used to perform linear regression where there are repeated measures from the same subject (factor1)

```{r, echo=F}
require(lme4)

for (i in 1:length(numericlist)) {
  if (i == 1) {
    formulas = paste(numericlist[i], '~')
  }else{
    formulas = paste(formulas, numericlist[i], "+")
  }
}

formulas <- as.formula(paste(formulas, " (1 | factor1)"))
# print(formulas)
formulas2 <- as.formula(paste(numericlist[1], "~", " 1 + (1 | factor1)"))
# print(formulas2)

```

```{r}
# mymodel = lmer(numeric1 ~ numeric2 + numeric3 + (1 | factor1), data= mydf)
mymodel = lmer(formulas, data = na.omit(mydf))
mymodel
anova(mymodel, lmer(formulas2, data = na.omit(mydf)))
```

